<Project Sdk="Microsoft.NET.Sdk.Worker"><PropertyGroup><AssemblyName>Olga.Core.Worker</AssemblyName></PropertyGroup><ItemGroup><ProjectReference Include="..\Olga.Core.Infrastructure\Olga.Core.Infrastructure.csproj" /><PackageReference Include="Azure.Identity" Version="1.21.0" /><PackageReference Include="Azure.Messaging.ServiceBus" Version="7.20.1" /><PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.12" /></ItemGroup></Project>
